version: '3'

services:
  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    restart: 'no'
    networks:
      - default

  postgres-db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dockerpostgres
      PG_DATA: /home/luanss/dev/docker-volumes/kotlin-spring-start/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - default
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24

volumes:
  pgdata: